spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true      # (2) SQL ?? ??
  output:
    ansi:
      enabled: ALWAYS
logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
server:
  servlet:
    encoding:
      force-response: true
mail:
  address:
    admin: admin@gmail.com
jwt:
  secret-key: 123           # 민감한 정보는 시스템 환경 변수에서 로드한다.
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420
cloud:
  aws:
    credentials:
      accessKey: tmp-access-key
      secretKey: tmp-secret-key
    region.static: ap-northeast-2
    stack.auto: false
    s3.bucketName: my-springboot-build

---

spring:
  config:
    activate:
      on-profile: dev # dev 환경 전용 설정 (위의 기본 설정을 덮어쓰는 방식)
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${RDS_URL}
    username: ${RDS_USERNAME}
    password: ${RDS_PWD}
  jpa:
    hibernate:
      ddl-auto: update # 운영 서버에서는 create 하면 X
  h2:
    console:
      enabled: false
cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY} # 키 절대 노출 금지
      secretKey: ${AWS_SECRET_KEY} # 키 절대 노출 금지
    region.static: ap-northeast-2
    stack.auto: false
    s3.bucketName: my-springboot-build
