spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true      # (2) SQL ?? ??
  output:
    ansi:
      enabled: ALWAYS
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 1051335177358-5ih47gcpocs6gpu2cmtd2ivrvcof968e.apps.googleusercontent.com
            clientSecret: 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
logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
server:
  servlet:
    encoding:
      force-response: true
mail:
  address:
    admin: admin@gmail.com
jwt:
  secret-key: ${JWT_SECRET_KEY}           # 민감한 정보는 시스템 환경 변수에서 로드한다.
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420


---

spring:
  config:
    activate:
      on-profile: dev # dev 환경 전용 설정 (위의 기본 설정을 덮어쓰는 방식)
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${RDS_URL}
    username: ${RDS_USERNAME}
    password: ${RDS_PWD}
  jpa:
    hibernate:
      ddl-auto: update # 운영 서버에서는 create 하면 X
  h2:
    console:
      enabled: false