spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: create  # ? ???? ??? ?? ? ??? -> ????!! (test server : update, validate ??, ????, ???? : validate, none ??)
    show-sql: true      # (2) SQL ?? ??
  output:
    ansi:
      enabled: ALWAYS
logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG